---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eqp
  name: eqp
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eqp
  template:
    metadata:
      annotations:
        prometheus.io/port: '2112'
        prometheus.io/scrape: 'true'
      labels:
        app: eqp
    spec:
      containers:
      - name: eqp
        image: tomdoherty/eqp:v0.0.6
        env:
        - name: ELASTICSEARCH_HOST
          value: "https://elasticsearch-es-http.elastic-system.svc:9200"
        - name: ELASTICSEARCH_USER
          value: "elastic"
        - name: CONFIG_FILE
          value: "/matchers.yaml"
        - name: FREQUENCY
          value: "20s"
        - name: VERIFY_TLS
          value: "false"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-user
              key: password

        volumeMounts:
        - name: config
          mountPath: /matchers.yaml

        ports:
        - containerPort: 2112
          name: metrics
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: 2112
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 2112
            scheme: HTTP
    volumes:
    - name: config
      configMap:
        name: eqp-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eqp-config
  namespace: kube-system
data:
  matchers.yaml: |
    matches:
    - name: ErrorMessage
      pattern: .*error.*
      type: regexp
      index: log-syslog-serverlog-kubernetes-*
    - name: WarnMessage
      pattern: .*warning.*
      type: regexp
      index: log-syslog-serverlog-kubernetes-*

---
apiVersion: v1
kind: Service
metadata:
  name: eqp-metrics
  namespace: kube-system
  labels:
    app: eqp
spec:
  type: ClusterIP
  selector:
    app: eqp
  ports:
  - name: metrics
    port: 2112
    protocol: TCP
    targetPort: 2112

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eqp-metrics
  namespace: kube-system
  labels:
    app: eqp
spec:
  jobLabel: "app.kubernetes.io/name"
  selector:
    matchLabels:
      app: eqp
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
